version: "3.1"
services:
    sylius-webserver:
        build: docker/webserver
        container_name: sylius-webserver
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/sylius
            - sylius-var:/var/www/sylius/var
            - ./docker/webserver/nginx.conf:/etc/nginx/sites-available/default
            - ./docker/webserver/php.ini:/etc/php/8/fpm/conf.d/99-overrides.ini
        networks:
            sylius:
                aliases:
                    - sylius.local

    sylius-database:
        build: docker/database
        container_name: sylius-database
        ports:
            - "8007:5432"
        volumes:
            - sylius-database-postgres:/var/lib/postgresql
            - ./docker/database/pg_hba.conf:/etc/postgresql/11/main/pg_hba.conf
            - ./docker/database/postgresql.conf:/etc/postgresql/11/main/postgresql.conf
        networks:
            - sylius

volumes:
    sylius-var:
    sylius-database-postgres:

networks:
    sylius:
